package org.ce.ap.discord.common.entity.api.enumeration;

import java.io.Serializable;

/**
 * @author Parham Ahmady
 * @since 6/1/2022
 */
public enum HeaderType implements Serializable {
    ERROR("ERROR"),
    SERVER_SHUTDOWN("SERVER_SHUTDOWN"),
    CLIENT_SHUTDOWN("CLIENT_SHUTDOWN"),

    //Authentication
    LOG_IN_REQUEST("LOG_IN_REQUEST"),
    LOG_IN_RESPONSE("LOG_IN_RESPONSE"),
    LOG_OUT_REQUEST("LOG_OUT_REQUEST"),
    LOG_OUT_RESPONSE("LOG_OUT_RESPONSE"),
    REGISTER_RESPONSE("REGISTER_RESPONSE"),
    REGISTER_REQUEST("REGISTER_REQUEST"),

    //ServerManagement
    ADD_SERVER_REQUEST("ADD_SERVER_REQUEST"),
    ADD_SERVER_RESPONSE("ADD_SERVER_RESPONSE"),
    ADD_CHANNEL_REQUEST("ADD_CHANNEL_REQUEST"),
    ADD_CHANNEL_RESPONSE("ADD_CHANNEL_RESPONSE"),
    ADD_CATEGORY_REQUEST("ADD_CATEGORY_REQUEST"),
    ADD_CATEGORY_RESPONSE("ADD_CATEGORY_RESPONSE"),
    REMOVE_SERVER_MEMBER_REQUEST("REMOVE_SERVER_MEMBER_REQUEST"),
    REMOVE_SERVER_MEMBER_RESPONSE("REMOVE_SERVER_MEMBER_RESPONSE"),
    ADD_PERSON_REQUEST("ADD_PERSON_REQUEST"),
    ADD_PERSON_RESPONSE("ADD_PERSON_RESPONSE"),
    SET_ROLE_REQUEST("SET_ROLE_REQUEST"),
    SET_ROLE_RESPONSE("SET_ROLE_RESPONSE"),
    REMOVE_CHANNEL_REQUEST("REMOVE_CHANNEL_REQUEST"),
    REMOVE_CHANNEL_RESPONSE("REMOVE_CHANNEL_RESPONSE"),
    GET_SERVER_MEMBERS_REQUEST("GET_SERVER_MEMBERS_REQUEST"),
    GET_SERVER_MEMBERS_RESPONSE("GET_SERVER_MEMBERS_RESPONSE"),
    GET_SERVER_CHANNELS_REQUEST("GET_SERVER_CHANNELS_REQUEST"),
    GET_SERVER_CHANNELS_RESPONSE("GET_SERVER_CHANNELS_RESPONSE"),
    SELECT_CHANNEL_REQUEST("SELECT_CHANNEL_RESPONSE"),
    SELECT_CHANNEL_RESPONSE("SELECT_CHANNEL_RESPONSE"),
    RENAME_SERVER_REQUEST("RENAME_SERVER_REQUEST"),
    RENAME_SERVER_RESPONSE("RENAME_SERVER_RESPONSE"),
    SELECT_SERVER_REQUEST("SELECT_SERVER_REQUEST"),
    SELECT_SERVER_RESPONSE("SELECT_SERVER_RESPONSE"),
    SEND_CHANNEL_MSG_REQUEST("SEND_CHANNEL_MSG_REQUEST"),
    SEND_CHANNEL_MSG_RESPONSE("SEND_CHANNEL_MSG_RESPONSE"),
    REACT_REQUEST("REACT_REQUEST"),
    REACT_RESPONSE("REACT_RESPONSE"),

    //UserManagement
    UPDATE_PERSON_REQUEST("UPDATE_PERSON_REQUEST"),
    UPDATE_PERSON_RESPONSE("UPDATE_PERSON_RESPONSE"),
    CHANGE_PWD_REQUEST("CHANGE_PWD_REQUEST"),
    CHANGE_PWD_RESPONSE("CHANGE_PWD_RESPONSE"),
    CHANGE_IMG_REQUEST("CHANGE_IMG_REQUEST"),
    CHANGE_IMG_RESPONSE("CHANGE_IMG_RESPONSE"),
    GET_FRIEND_LIST_REQUEST("GET_FRIEND_LIST_REQUEST"),
    GET_FRIEND_LIST_RESPONSE("GET_FRIEND_LIST_RESPONSE"),
    GET_BLOCK_LIST_REQUEST("GET_BLOCK_LIST_REQUEST"),
    GET_BLOCK_LIST_RESPONSE("GET_BLOCK_LIST_RESPONSE"),
    GET_FRIEND_REQUESTS_REQUEST("GET_FRIEND_REQUESTS_REQUEST"),
    GET_FRIEND_REQUESTS_RESPONSE("GET_FRIEND_REQUESTS_RESPONSE"),
    GET_CHATS_REQUEST("GET_CHATS_REQUEST"),
    GET_CHATS_RESPONSE("GET_CHATS_RESPONSE"),
    GET_SERVERS_LIST_REQUEST("GET_SERVERS_LIST_REQUEST"),
    GET_SERVERS_LIST_RESPONSE("GET_SERVERS_LIST_RESPONSE"),

    //ChatManagement
    SEND_FRIEND_REQUEST_REQUEST("SEND_FRIEND_REQUEST_REQUEST"),
    SEND_FRIEND_REQUEST_RESPONSE("SEND_FRIEND_REQUEST_RESPONSE"),
    ACCEPT_FRIEND_REQUEST_REQUEST("ACCEPT_FRIEND_REQUEST_REQUEST"),
    ACCEPT_FRIEND_REQUEST_RESPONSE("ACCEPT_FRIEND_REQUEST_RESPONSE"),
    REJECT_FRIEND_REQUEST_REQUEST("REJECT_FRIEND_REQUEST_REQUEST"),
    REJECT_FRIEND_REQUEST_RESPONSE("REJECT_FRIEND_REQUEST_RESPONSE"),
    BLOCK_REQUEST("BLOCK_REQUEST"),
    BLOCK_RESPONSE("BLOCK_RESPONSE"),
    UNBLOCK_REQUEST("UNBLOCK_REQUEST"),
    UNBLOCK_RESPONSE("UNBLOCK_RESPONSE"),
    SEND_PRIVATE_MESSAGE_REQUEST("SEND_PRIVATE_MESSAGE_REQUEST"),
    SEND_PRIVATE_MESSAGE_RESPONSE("SEND_PRIVATE_MESSAGE_RESPONSE");

    public final String type;

    HeaderType(String type) {
        this.type = type;
    }
}